Repository publiclab/mapknitter, pull requests merged in 2019-04, with the labels that each got.

#462 Dynamic ports
  .env
  Makefile
  docker-compose.yml
Labels: ready

#498 Changed the new map modal text
  app/views/layouts/knitter2.html.erb
Labels: ready

#505 Choose keyserver known to have our GPG key
  Dockerfile
Labels: ready

#493 Update Gemfile.lock / README for Ruby 2.4.6
  Gemfile.lock
  README.md
Labels: documentation, installation, ready

#525 Update Contributing.md syntax mistake
  CONTRIBUTING.md
Labels: documentation, ready

#483 Create Status.json
  app/controllers/export_controller.rb
  app/models/map.rb
  app/views/maps/_sidebar_exports.html.erb
  config/routes.rb
Labels: ready

#537 add required in Login
  app/views/layouts/_login_form.html.erb
Labels: enhancement, ready

#557 Data fetching
  app/controllers/sessions_controller.rb
Labels: needs review

#562 Solve image uploads bugs
  app/views/images/_new.html.erb
Labels: bug, ready

#555 Update LDI to newest release 0.4.2
  bower.json
Labels: dependencies

#561 Creation of OAuth route for MK
  app/controllers/sessions_controller.rb
  app/views/layouts/_login_form.html.erb
Labels: needs-review, ready
