Repository publiclab/mapknitter, pull requests merged in 2019-06, with the labels that each got.

#615 Add tests for controllers
  app/models/export.rb
  db/schema.rb
  test/fixtures/annotations.yml
  test/fixtures/exports.yml
  test/functional/annotations_controller_test.rb
  test/functional/comments_controller_test.rb
  test/functional/export_controller_test.rb
  test/functional/feeds_controller_test.rb
  test/functional/images_controller_test.rb
  test/functional/maps_controller_test.rb
  test/functional/sessions_controller_test.rb
  test/functional/tags_controller_test.rb
  test/functional/users_controller_test.rb
  test/functional/utility_controller_test.rb
  test/reports/TEST-ExportTest.xml
  test/reports/TEST-MapTest.xml
  test/reports/TEST-MapsControllerTest.xml
  test/reports/TEST-UserTest.xml
Labels: ready

#610 Add new tests for models
  app/models/map.rb
  app/models/user.rb
  test/unit/annotation_test.rb
  test/unit/export_test.rb
  test/unit/exporter_test.rb
  test/unit/map_test.rb
  test/unit/node_test.rb
  test/unit/tag_test.rb
  test/unit/user_test.rb
  test/unit/warpable_test.rb
Labels: ready

#674 Add margin to sidebar content
  app/assets/stylesheets/maps.css.scss
Labels: ready

#675 Reverse map refresh bug
  app/models/map.rb
Labels: bug, priority, ready

#652 Update README.md
  README.md
Labels: ready

#701 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, outreach

#718 Updated Installation Instructions Fixes #711
  README.md
Labels: ready

#695 Update README.md MapKnitter Spelling
  MYSQL.md
  README.md
Labels: documentation, ready

#726 Fix typo in MYSQL.md
  MYSQL.md
Labels: ready
