Repository publiclab/mapknitter, pull requests merged in 2019-08, with the labels that each got.

#862 Version tracking of images
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/images_controller.rb
  app/models/warpable.rb
  app/views/images/_index.html.erb
  config/environments/test.rb
  config/initializers/paper_trail.rb
  config/routes.rb
  db/migrate/20190715092943_create_versions.rb
  test/functional/images_controller_test.rb
Labels: gsoc, ready

#892 Map location not loading fix / other bug fixes (no more errors in terminal)!
  app/assets/javascripts/Google.js
  app/assets/javascripts/application.js
  app/assets/javascripts/mapknitter/Annotations.js
  app/assets/javascripts/mapknitter/Map.js
  app/assets/javascripts/maps.js
  app/assets/javascripts/tags.js
  app/assets/javascripts/uploads.js
  app/assets/stylesheets/application.scss
  app/views/images/_index.html.erb
  app/views/images/_new.html.erb
  app/views/layouts/knitter2.html.erb
  app/views/map/_annotations.html.erb
  app/views/map/_leaflet.html.erb
  app/views/maps/_geocoder.js.erb
  app/views/maps/annotate.html.erb
  app/views/maps/index.html.erb
  app/views/maps/show.html.erb
  package.json
  yarn.lock
Labels: needs-review

#905 Fixed repeated word in Statistics page issue #897
  app/views/maps/_statistics.html.erb
Labels: ready

#936 Configure System tests
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  lib/exporter-deps.sh
  test/application_system_test_case.rb
  test/system/searches_test.rb
Labels: ready

#923 UI improvements: version tracking and other in the sidebar
  app/assets/stylesheets/sidebar.css
  app/views/images/_index.html.erb
Labels: ready

#951 Fix image placement
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  config/environments/test.rb
  db/schema.rb
  test/system/images_test.rb
  test/test_helper.rb
Labels: bug, priority, ready

#805 action cable setup
  Gemfile
  Gemfile.lock
  Procfile
  SYNCHRONOUS_EDITING.md
  app/assets/javascripts/application.js
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/concurrent_editing.js
  app/assets/javascripts/mapknitter/Map.js
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/channels/concurrent_editing_channel.rb
  app/controllers/application_controller.rb
  app/controllers/images_controller.rb
  app/models/map.rb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/puma.rb
  config/routes.rb
  start.sh
  test/channels/concurrent_editing_channel_test.rb
  test/channels/connection_test.rb
  test/fixtures/maps.yml
  test/fixtures/nodes.yml
  test/system/synchronous_editing_test.rb
Labels: needs-review

#956 Setting Action Cable
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Procfile
  SYNCHRONOUS_EDITING.md
  app/assets/javascripts/application.js
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/concurrent_editing.js
  app/assets/javascripts/mapknitter/Map.js
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/channels/concurrent_editing_channel.rb
  app/controllers/application_controller.rb
  app/controllers/images_controller.rb
  app/models/map.rb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/assets.rb
  config/puma.rb
  config/routes.rb
  start.sh
  test/channels/concurrent_editing_channel_test.rb
  test/channels/connection_test.rb
  test/fixtures/maps.yml
  test/fixtures/nodes.yml
  test/system/synchronous_editing_test.rb
Labels: ready
