Repository publiclab/mapknitter, pull requests merged in 2019-09, with the labels that each got.

#944 change to factory syntax
  app/assets/javascripts/mapknitter/Annotations.js
Labels: ready

#992 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: ready

#995 Setting ForeGO instead of Foreman
  Dockerfile
  Gemfile
  Gemfile.lock
  start.sh
Labels: enhancement, ready

#1001 Fix broken tests
  Gemfile
  Gemfile.lock
  app/assets/javascripts/mapknitter/core/Class.js
  app/views/maps/show.html.erb
  test/controllers/front_ui_controller_test.rb
  test/controllers/maps_controller_test.rb
  test/system/images_test.rb
Labels: bug, needs-review, priority

#959 Implementgroup
  README.md
  app/assets/javascripts/mapknitter/Map.js
  app/views/layouts/knitter2.html.erb
  config/initializers/column_definition.rb
  config/puma.rb
  db/migrate/20091016214109_create_maps.rb
  db/migrate/20100308193343_add_map_description_author.rb
  db/migrate/20100316142953_zoom_to_float.rb
  db/migrate/20111005211631_add_zip_warpable_res_history.rb
  db/migrate/20111006153011_add_map_tile_url.rb
  db/migrate/20120104164144_add_export_type_bands.rb
  db/migrate/20130128184718_add_node_and_way_body.rb
  db/migrate/20141104184417_change_openid_identity_urls.rb
  db/migrate/20150715162314_change_map_null.rb
  db/migrate/20190909224739_remove_text_column_type_defaults.rb
  db/schema.rb
  db/schema.rb.example
  package.json
  yarn.lock
Labels: needs-review

#1011 Fix front ui
  app/assets/stylesheets/style.scss
  app/views/front_ui/index.html.erb
  app/views/layouts/_login_form.html.erb
Labels: bug, cleanup, ready

#1017 Restore anon edits
  app/assets/javascripts/mapknitter/Map.js
  app/controllers/images_controller.rb
  app/controllers/maps_controller.rb
  app/models/map.rb
  app/views/layouts/knitter2.html.erb
  app/views/maps/show.html.erb
  db/migrate/20190913045600_add_display_welcome_to_maps.rb
  db/schema.rb
  db/schema.rb.example
  test/controllers/images_controller_test.rb
  test/controllers/maps_controller_test.rb
  test/fixtures/maps.yml
  test/fixtures/warpables.yml
Labels: bug, priority, ready

#880 Update README.md Installation Readability
  README.md
Labels: documentation, ready
