Repository publiclab/mapknitter, pull requests merged in 2019-07, with the labels that each got.

#749 Attempt to fix broken coverage reports
  .codecov.yml
  .simplecov
  Gemfile
  Gemfile.lock
  test/test_helper.rb
Labels: ready

#768 update codenvy install script and readme
  Gemfile
  Gemfile.lock
  README.md
  install_cloud.sh
Labels: bug, installation, needs-review

#640 Image ordering in sidebar using sorting options
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/sidebar.css
  app/views/images/_index.html.erb
Labels: needs-review

#803 Fixing mismatching dependencies
  .gitignore
  Dockerfile
  docker-compose.yml
  start.sh
  yarn.lock
Labels: help wanted

#826 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, outreach

#847 Exclude .idea directory from tracking
  .gitignore
Labels: ready

#854 Remove 2nd easybutton dependency
  package.json
  yarn.lock
Labels: dependencies

#863 Update LDI to 0.6.3
  app/assets/javascripts/mapknitter/Map.js
  package.json
  yarn.lock
Labels: dependencies, ready

#864 Chat-in-different-ways button
  README.md
Labels: fto-in-progress

#819 Update installation docs
  MYSQL.md
  README.md
Labels: documentation, installation, needs-review

#876 Running test on one file added in README.md
  README.md
Labels: ready
