Repository publiclab/mapknitter, pull requests merged in 2019-05, with the labels that each got.

#552 Add remote_url to export model
  Gemfile
  Gemfile.lock
  app/controllers/export_controller.rb
  app/models/export.rb
  app/services/exporter_client.rb
  config/routes.rb
  db/migrate/20190420025012_add_remote_url_to_exports.rb
  db/schema.rb
Labels: needs-review

#451 improve toggle sidebar
  app/assets/javascripts/maps.js
  app/views/layouts/knitter2.html.erb
Labels: JavaScript, bug

#516 Added leaflet-fullhash library
  app/views/maps/index.html.erb
  bower.json
  public/owmloading.gif
Labels: ready

#575 (don't merge yet) Removal of username from Login
  app/controllers/sessions_controller.rb
  app/views/layouts/_login_form.html.erb
Labels: ready

#512 Completely removing leaflet-hash module
  app/views/maps/index.html.erb
Labels: ready

#611 Update seeds.rb
  README.md
  config/config.yml.example
  db/seeds.rb
Labels: ready

#637 Singularization Issue Fixed
  app/views/maps/_list.html.erb
Labels: ready

#643 Functional tests - testing env fix
  app/controllers/sessions_controller.rb
  config/config.yml.example
  db/schema.rb
  db/seeds.rb
  test/functional/sessions_controller_test.rb
Labels: ready

#629 header search bar stays together
  app/views/layouts/_header.html.erb
Labels: bug, ready

#630 Backend search constraints (length & whitespace)
  app/controllers/maps_controller.rb
  app/models/map.rb
  app/views/layouts/_header.html.erb
  config/application.rb
  lib/not_at_origin_validator.rb
Labels: enhancement, needs-review
